package com.babyspace.mamshare.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.babyspace.mamshare.framework.db.DaoSession;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table MArea.
 */
public class CityAreaDao extends AbstractDao<CityArea, String> {

    public static final String TABLENAME = "MArea";

    /**
     * Properties of entity Note.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {

        public final static Property areaId = new Property(0, String.class, "areaId", false, "areaId");
        public final static Property areaType = new Property(1, String.class, "areaType", false, "areaType");
        public final static Property areaName = new Property(2, String.class, "areaName", false, "areaName");
        public final static Property parentId = new Property(3, String.class, "parentId", false, "parentId");
        public final static Property zip = new Property(4, String.class, "zip", false, "zip");
    }

    public CityAreaDao(DaoConfig config) {
        super(config);
    }

    public CityAreaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'MArea' (" + //
                "'areaId' TEXT NOT NULL PRIMARY KEY ," + // 1: 哈哈
                "'areaType' TEXT," + // 2: 类型
                "'areaName' TEXT NOT NULL," + // 3: 名字
                "'parentId' TEXT NOT NULL," + // 4: 上一个
                "'zip' TEXT);"); // 5: 邮编
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MArea'";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, CityArea entity) {
        stmt.clearBindings();

        stmt.bindString(1, entity.getAreaId());
        stmt.bindString(2, entity.getAreaType());
        stmt.bindString(3, entity.getAreaName());
        stmt.bindString(4, entity.getParentId());
        stmt.bindString(5, entity.getZip());

    }

    /**
     * @inheritdoc
     */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public CityArea readEntity(Cursor cursor, int offset) {
        CityArea entity = new CityArea( //
                cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
                cursor.getString(offset + 1), // text
                cursor.getString(offset + 2), // text
                cursor.getString(offset + 3), // text
                cursor.getString(offset + 4) // text

        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, CityArea entity, int offset) {
        entity.setAreaId(cursor.getString(offset + 0));
        entity.setAreaType(cursor.getString(offset + 1));
        entity.setAreaName(cursor.getString(offset + 2));
        entity.setParentId(cursor.getString(offset + 3));
        entity.setZip(cursor.getString(offset + 4));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected String updateKeyAfterInsert(CityArea entity,long rowId) {
        entity.setAreaId(entity.getAreaId());
        return entity.getAreaId();
    }

    /**
     * @inheritdoc
     */
    @Override
    public String getKey(CityArea entity) {
        if (entity != null) {
            return entity.getAreaId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return false;
    }

}
